// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: protocols/postaci.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId    uint64 `protobuf:"varint,1,opt,name=mailId,proto3" json:"mailId,omitempty"`
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *ForwardMailRequest) Reset() {
	*x = ForwardMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_postaci_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMailRequest) ProtoMessage() {}

func (x *ForwardMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_postaci_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMailRequest.ProtoReflect.Descriptor instead.
func (*ForwardMailRequest) Descriptor() ([]byte, []int) {
	return file_protocols_postaci_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardMailRequest) GetMailId() uint64 {
	if x != nil {
		return x.MailId
	}
	return 0
}

func (x *ForwardMailRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

type ForwardMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Error      string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ForwardMailResponse) Reset() {
	*x = ForwardMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_postaci_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMailResponse) ProtoMessage() {}

func (x *ForwardMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_postaci_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMailResponse.ProtoReflect.Descriptor instead.
func (*ForwardMailResponse) Descriptor() ([]byte, []int) {
	return file_protocols_postaci_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardMailResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *ForwardMailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protocols_postaci_proto protoreflect.FileDescriptor

var file_protocols_postaci_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74,
	0x61, 0x63, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x46, 0x6f, 0x72,
	0x77, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x49, 0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0b, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x61,
	0x69, 0x6c, 0x12, 0x13, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_postaci_proto_rawDescOnce sync.Once
	file_protocols_postaci_proto_rawDescData = file_protocols_postaci_proto_rawDesc
)

func file_protocols_postaci_proto_rawDescGZIP() []byte {
	file_protocols_postaci_proto_rawDescOnce.Do(func() {
		file_protocols_postaci_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_postaci_proto_rawDescData)
	})
	return file_protocols_postaci_proto_rawDescData
}

var file_protocols_postaci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocols_postaci_proto_goTypes = []interface{}{
	(*ForwardMailRequest)(nil),  // 0: ForwardMailRequest
	(*ForwardMailResponse)(nil), // 1: ForwardMailResponse
}
var file_protocols_postaci_proto_depIdxs = []int32{
	0, // 0: MailingServer.ForwardMail:input_type -> ForwardMailRequest
	1, // 1: MailingServer.ForwardMail:output_type -> ForwardMailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocols_postaci_proto_init() }
func file_protocols_postaci_proto_init() {
	if File_protocols_postaci_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_postaci_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_postaci_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_postaci_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocols_postaci_proto_goTypes,
		DependencyIndexes: file_protocols_postaci_proto_depIdxs,
		MessageInfos:      file_protocols_postaci_proto_msgTypes,
	}.Build()
	File_protocols_postaci_proto = out.File
	file_protocols_postaci_proto_rawDesc = nil
	file_protocols_postaci_proto_goTypes = nil
	file_protocols_postaci_proto_depIdxs = nil
}
