version: '3.4'
services:
  postaci:
    build: 
      context: postaci
    restart: always
    env_file: ./postaci/.env
    ports:
      - "5000:5000"
    volumes:
      - "/root/Maildir/:/root/Maildir/"